### ISSUE TITLE
Improve forward-sexp, mark-sexp and so on

### ISSUE THREAD

**Issue by semente** [fxbois/web-mode#102]
That might be complicated, but well, the behavior of some Emacs commands is not the same as in html-mode and other Emacs mode, as for example `C-M-f` (forward-sexp).

**Comment by Ergus** [comment]
Hi:
Sorry for necro-pumping this but I have seen that this issue is still somehow alive. Since 2013 emacs has changed a lot and now the commands to navegate has been updated/fixed. I am somehow wondering why webmode does not use the default bindings as well (ex. C-c C-n === C-M-n). 

Also mark-sexp (C-M-SPC) does not work in php files as expected because the binding is set to a function that only works in html mode/tags.

If there are some bindings already functional, why do you change their behavior?
