### ISSUE TITLE
Engine blocks in comments being "uncommented"

### ISSUE THREAD

**Issue by yuhan0** [fxbois/web-mode#1091]
With single file components like Vue or Svelte, commented-out text in a `<script>` block is wrongly parsed as uncommented code when the syntax defined in `web-mode-engines-auto-pairs` is present, and appears instead as various syntax errors.

eg. in a file example.vue
```html
<script>
 // foo bar
 // baz {{  this should
 // still be treated as
 // a comment }}
</script>

```

Actual behavior:
![image](https://user-images.githubusercontent.com/22216124/67546308-af1d4c80-f72e-11e9-8eaf-bdead4aa587a.png)

**Comment by fxbois** [comment]
@yuhan0 I can not trigger the issue. Try with a very simple .emacs that only web-mode stuffs

**Comment by yuhan0** [comment]
I was able to reproduce it with the bare minimum `emacs -Q` and `(load "path/to/web-mode.el")`,  on emacs 26.3, macOS 10.15.

Note that the visited file in the above example has to have a `.vue` extension in order for the issue to occur.

**Comment by fxbois** [comment]
@yuhan0 ok I understand. ```{{ }}``` are blocks in vue template. So this behaviour is normal. Backend blocks are priority over client tokens (comments, strings)

**Comment by MilanKladivko** [comment]
In languages such as Svelte, this does some funky stuff. 

It uses a really basic `<input id={id}>` -- only a single curly. 

And that occurs everywhere, both in CSS and TS code, breaking with every line that has both the opening and closing curlies.
In some rare cases, it really messes up indentation -- when commenting code for example. 

Not saying it should be fixed -- it's probably what "web-mode" is supposed to do for backend-based PHP-style templating... 

But it's not what Svelte specifically does in `.svelte` files -- it uses templating only in the HTML markup, excluding the script and style tags. \
So, for anybody else having the issue, here's my snippet of code that overwrites the array that has the template delimiters with a garbage one assigned to Svelte so that it never gets matched. \
When working with LSP, I don't need the highlighting and LSP still understands the syntax completely separately from the editor anyway. 

```
  ;;   The template parens get applied even though it's in <script> which
  ;;   breaks not only colors but sometimes even indentation -- that gets really messy.
  ;;   https://github.com/fxbois/web-mode/issues/1091
  (setq-default
   web-mode-engine-open-delimiter-regexps
   (list
    '("svelte"           . "oh web mode, you can't even svelte {.")
    
    ;; And then copy over the rest of the list -- I don't even know how
    ;; to modify arrays in elisp
    '("angular"          . "{{")
    '("asp"              . "<%\\|</?[[:alpha:]]+:[[:alpha:]]+\\|</?[[:alpha:]]+Template")
    '("aspx"             . "<%.")
    '("django"           . "{[#{%]\\|^#")
    '("elixir"           . "<%")
    '("go"               . "{{.")
    '("php"              . "<\\?")
    '("python"           . "<\\?")
    '("vue"              . "{{\\|[:@][-[:alpha:]]+=\"")
    ))
```
