### ISSUE TITLE
Support Jekyll (Liquid + YAML)

### ISSUE THREAD

**Issue by DamienCassou** [fxbois/web-mode#123]
The popular Jekyll static website generator uses what looks like a combination of both Liquid and YAML for its templates. A typical template looks like:

``` html

---
layout: default

---

  <section class="docs">
    <div class="grid">

      {% include docs_contents_mobile.html %}

      <div class="unit four-fifths">
        <article>
          <h1>{{ page.title }}</h1>
          {{ content }}
          {% include section_nav.html %}
        </article>
      </div>

      {% include docs_contents.html %}

      <div class="clear"></div>

    </div>
  </section>
```

Some links:
- http://jekyllrb.com
- http://jekyllrb.com/docs/templates/
- http://jekyllrb.com/docs/frontmatter/

**Comment by azzamsa** [comment]
is this issue resolved?

I think [it's the related commit](https://github.com/fxbois/web-mode/commit/3621cf7b6aa5e8faf7036ce5877a5a7e7f5547aa)

I am using the latest revision of web-mode. But whenever I type anything in the yaml front-matter, web-mode always indent those line. Is there any way for web-mode to ignore everything in front-matter?

![Peek 2020-07-09 06-14](https://user-images.githubusercontent.com/17734314/86979428-7ed9e900-c1ab-11ea-9e69-a5bc5d6ea72c.gif)

I think setting `web-mode-engines-alist` to liquid or nunjucks doesn't help, since it's already [the default](https://github.com/fxbois/web-mode/blob/60ffd878c4371644bd964f00fea38054645e3e47/web-mode.el#L883)

The best that web-mode can do is ignore the front-matter at all.

notes:
- [Eleventy frontmatter](https://www.11ty.dev/docs/data-frontmatter/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

Thank you for web-mode.

**Comment by DamienCassou** [comment]
I suggest you open a new issue and reference this one.

**Comment by azzamsa** [comment]
@DamienCassou I think it's a same problem. Does this issue resolved in your end?

**Comment by DamienCassou** [comment]
azzamsa <notifications@github.com> writes:
> @DamienCassou I think it's a same problem. Does this issue resolved in your end?

I don't remember, this was a long time ago. I haven't done any website
for some time now :-).

Creating a new issue will make your problem more visible because you are
commenting on a very old and closed issue.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
