### ISSUE TITLE
Broken web-mode-on-post-command with current-column-highlight

### ISSUE THREAD

**Issue by jyasskin** [fxbois/web-mode#412]
With `Web Mode Enable Current Column Highlight` on, when I cursor over an element, I get:

> Error in post-command-hook (web-mode-on-post-command): (error "Wrong number of arguments")

and the rest of web-mode stops working.

**Comment by fxbois** [comment]
@jyasskin I can not reproduce the issue
do you have the last version available on github ?
Moreover could you 
- post the example that triggers the bug 
- post the web-mode related stuff of your .emacs

**Comment by fxbois** [comment]
@jyasskin please reopen when you can provide more infos

**Comment by notetiene** [comment]
I can confirm that this bug works. I tried with my usual config file and a new one and both fail.
Code to reproduce
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>

<!-- Note just before this line an empty newline -->
    </body>
</html>
</html>
```
Activate column-highlight.

Since I'm new to elisp, I wasn't able to find the bug, I tried 2 hours (or more),
It is probably located in web-mode-column-show. I think it's because it's trying to access a position that doesn't exist since *it will work* if I add the needed indentation.
![cap](https://cloud.githubusercontent.com/assets/5413838/6344854/803ab47c-bbcc-11e4-9fec-843fcc5fce0f.png)

**Comment by fxbois** [comment]
@notetiene do you have the last version on github ?

**Comment by fxbois** [comment]
@notetiene could you try the last version on github please

**Comment by notetiene** [comment]
Thanks a lot! It now works pretty well!
