### ISSUE TITLE
no indentation on specific tags (like head, meta, script, etc)

### ISSUE THREAD

**Issue by mbriggs** [fxbois/web-mode#6]
Pretty sure this is intentional, but it would be awesome if this was a configurable property :)

**Comment by jasonm23** [comment]
Can we re-open this so that head elements `<link>` `<meta>`  do not need to be closed.

I know HTML has ridiculous laxity on elements, but these two are so often left unclosed that it's a  pain to have to do special manual indentation (and never re-indent the whole buffer) when dealing with documents that have been set this way. (and people sometimes edit war / or simply waste time "discussing" over the perceived correctness of closing `meta` and `link`.)

Obviously it's not a big priority, but I think leaving the issue open until these are fixed will at least avoid the same issue popping up in another post.

**Comment by jasonm23** [comment]
Oh and @mbriggs nice avatar ;)

**Comment by fxbois** [comment]
@jasonm23 it is already the case : see ```web-mode-void-elements```

**Comment by jasonm23** [comment]
It is I was being a dummy and using nXML mode :(


Sorry!
