### ISSUE TITLE
ac-php incompatibilty

### ISSUE THREAD

**Issue by fallchildren** [fxbois/web-mode#625]
ac-php (https://github.com/xcwen/ac-php) is not fully compatible with web-mode. ac-php sets ac-sources to "ac-source-php-template" after a completion which colides with web-modes (defadvice ac-start ...) on line 11198.
I don't know if this could be easier fixed in ac-php or web-mode.

Possible solution for web-mode:
check if ac-sources is set to "ac-source-php-template" before adjusting ac-sources 
```lisp
(defadvice ac-start ...
  (if (equal major-mode 'web-mode)
     ;; this line
    (when (not (equal 'ac-source-php-template (car ac-sources)))
      (progn ...
```

I know this is far from optimal and just a quick hack.

**Comment by fxbois** [comment]
I do not know anything about this.
Could you discuss this with @NateEag who has proposed this ```defadvice```

**Comment by fallchildren** [comment]
I created a pull request with a cleaner resolution to this problem. Maybe @NateEag can review the commit. But I think it's clean and not much of a big deal.

**Comment by NateEag** [comment]
@fallchildren I haven't done anything with PHP in Emacs for several years, so my memory of this code is rusty, and I have no experience of ac-php (which looks pretty nifty - wish it had been around when I was doing PHP).

That said, I *think* it might make more sense to handle this case in ac-php. If it's setting the ac-source after completion, it seems like it should try to avoid stomping on other ac-sources. Would it be possible for it to just add ac-source-php-template to the list of ac-sources, rather than making it the whole list?

web-mode's ac support would be easiest to maintain if it avoids knowing about specific ac-sources - it's forced to swap between sets of ac-sources by its very nature. Once we start adding custom hacks to it, that list of hacks will never stop growing, so I'd much prefer to avoid that if possible.

**Comment by NateEag** [comment]
@fallchildren somehow I totally missed your PR.

I prefer to avoid ac-source hackery, but your proposed solution looks reasonable to me - plenty of ac-sources do some variation on this theme, and that seems like a reasonable way to handle them.

**Comment by fxbois** [comment]
@fallchildren thx Nate for your advices
